---
# Create by App::VTide::Command::Init Wed May 15 09:11:23 2019 VERSION 0.1.8
count: 10
default:
  restart: 0
  wait: 0
editor:
  files:
    base:
      - lib/App/BambooCli.pm
      - lib/App/BambooCli/Config.pm
      - lib/App/BambooCli/Command.pm
    projects:
      - lib/App/BambooCli/Command/Projects.pm
      - lib/App/BambooCli/Command/Project.pm
      - lib/App/BambooCli/Command/Plans.pm
name: bamboo-cli
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2:
    edit:
      - base
  3:
    edit:
      - projects
  4: []

  5: []
